### ISSUE TITLE
First example on your page fails

### ISSUE THREAD

**Issue by tpylkko** [piever/GroupedErrors.jl#5] opened 2017-10-24 11:51 UTC
The first example in the readme leads to:

`ERROR: UndefVarError: @> not defined
`

**Comment by piever** [comment] 2017-10-24 12:40
I can't reproduce this... What's the full output that you get if you type say:

```julia
using GroupedErrors
@> 3 exp
```

or if you do:

```julia
using GroupedErrors
ProcessedTable
```
in a fresh julia session?

Maybe something went wrong with the installation, in which case I'd recommend to do `Pkg.build("GroupedErrors")` always in the Julia REPL and try again. To confirm that the installation was successful, you can do `Pkg.test("GroupedErrors")`.

The other option is that you could be in a very outdated version of Lazy.jl (one of the dependencies). What's the output of `Pkg.status("Lazy")`?

**Comment by tpylkko** [comment] 2017-10-25 17:42
It works now. Last time I copy pasted the code directly into the REPL, as I did now. The only thing that changed is that I restarted the REPL (cold booted machine today) and that I ran `Pkg.test("GroupedErrors")`

However, the test said that it "passed".

So, not much to go on, I guess...

also:
`Pkg.status("Lazy")
  Lazy                          0.12.0
`

**Comment by piever** [comment] 2017-10-31 15:07
Closing as it seems to have self fixed, I'll reopen if the issue reappears.

**Closed as completed by piever** 2017-10-31 15:07 UTC
